In [28]:
!pip install openpyxl

Requirement already satisfied: openpyxl in c:\program files\python312\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\program files\python312\lib\site-packages (from openpyxl) (2.0.0)

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [29]:
import pandas as pd
import matplotlib.pyplot as plt
df=pd.read_csv(r"/Users/Administrator/downloads/student_marksheet(new).csv")

# Question columns
question_cols = df.columns[1:]

# Total score
df["Total_Score"] = df[question_cols].sum(axis=1)

# Percentage
total_questions = len(question_cols)
df["Percentage"] = (df["Total_Score"] / total_questions) * 100
d=df.groupby('Percentage')['Total_Score'].size()
d

Percentage
35.714286     1
39.285714     1
42.857143     4
46.428571     3
50.000000     4
53.571429     6
57.142857    11
60.714286     3
64.285714    10
67.857143    10
71.428571     1
75.000000    10
78.571429     8
82.142857     9
85.714286     8
89.285714     5
92.857143     1
Name: Total_Score, dtype: int64

In [22]:
# Classification
def classify(student):
    if student >= 70:
        return "Advanced"

    else:
        return "Basic"

df["Category"] = df["Percentage"].apply(classify)
df

,Name,1,2,3,4,5,6,7,8,9,...,22,23,24,25,26,27,28,Total_Score,Percentage,Category
0,lli,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,21,75.000000,Advanced
1,tal,1,0,0,1,1,1,0,1,1,...,0,0,0,0,0,0,0,16,57.142857,Basic
2,ira,1,1,1,1,1,1,1,1,1,...,0,0,0,1,0,0,0,18,64.285714,Basic
3,ana,1,0,1,1,0,1,1,1,0,...,0,0,0,0,0,0,0,16,57.142857,Basic
4,wat,1,1,1,1,1,1,0,1,1,...,0,0,0,0,0,0,0,19,67.857143,Basic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90,cob,1,1,1,1,1,1,1,1,1,...,1,0,0,1,0,0,0,21,75.000000,Advanced
91,ash,1,1,1,1,1,1,1,1,1,...,1,0,0,1,0,0,1,23,82.142857,Advanced
92,ddy,1,0,1,1,1,1,1,1,1,...,0,0,0,1,0,0,1,16,57.142857,Basic
93,aju,1,1,1,1,1,1,1,1,1,...,0,0,0,1,1,0,0,19,67.857143,Basic
94,ppa,1,1,1,1,0,1,1,1,1,...,0,0,0,1,1,1,1,24,85.714286,Advanced

In [22]:
# Classification
def classify(student):
    if student >= 70:
        return "Advanced"

    else:
        return "Basic"

df["Category"] = df["Percentage"].apply(classify)
df

,Name,1,2,3,4,5,6,7,8,9,...,22,23,24,25,26,27,28,Total_Score,Percentage,Category
0,lli,1,1,1,1,1,1,1,1,1,...,0,0,0,0,0,0,0,21,75.000000,Advanced
1,tal,1,0,0,1,1,1,0,1,1,...,0,0,0,0,0,0,0,16,57.142857,Basic
2,ira,1,1,1,1,1,1,1,1,1,...,0,0,0,1,0,0,0,18,64.285714,Basic
3,ana,1,0,1,1,0,1,1,1,0,...,0,0,0,0,0,0,0,16,57.142857,Basic
4,wat,1,1,1,1,1,1,0,1,1,...,0,0,0,0,0,0,0,19,67.857143,Basic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90,cob,1,1,1,1,1,1,1,1,1,...,1,0,0,1,0,0,0,21,75.000000,Advanced
91,ash,1,1,1,1,1,1,1,1,1,...,1,0,0,1,0,0,1,23,82.142857,Advanced
92,ddy,1,0,1,1,1,1,1,1,1,...,0,0,0,1,0,0,1,16,57.142857,Basic
93,aju,1,1,1,1,1,1,1,1,1,...,0,0,0,1,1,0,0,19,67.857143,Basic
94,ppa,1,1,1,1,0,1,1,1,1,...,0,0,0,1,1,1,1,24,85.714286,Advanced

In [23]:
result=df[["Name", "Total_Score","Percentage", "Category"]]
result=result.sort_values(by="Category",ascending=False)

result.to_excel('genaitest1(new).xlsx',index=False)